bracketSpacing: true
printWidth: 100
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "es5"

overrides:
  - files: "*.sol"
    options:
      tabWidth: 4
      useTabs: false
      bracketSpacing: true
  - files: "*.ts"
    options:
      importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
      importOrderParserPlugins: ["typescript"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
