bracketSpacing: true
printWidth: 100
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "es5"
plugins:
  - "@trivago/prettier-plugin-sort-imports"

overrides:
  - files: "*.ts"
    options:
      importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
      importOrderParserPlugins: ["typescript"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
