# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
auto_detect_solc = false
broadcast = "broadcast"
bytecode_hash = "none"
cache_path = "foundry_cache"
fuzz_runs = 256
gas_reports = ["*"]
libs = ["node_modules", "lib"]
optimizer = true
optimizer_runs = 200
out = "out"
solc = "0.8.17"
src = "contracts"
script = "sol_script"
test = "sol_test"

[profile.ci]
fuzz_runs = 1_000
verbosity = 4
