# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
  auto_detect_solc = false
  bytecode_hash = "none"
  cbor_metadata = false
  evm_version = "paris"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  libs = ["node_modules", "lib"]
  optimizer = true
  optimizer_runs = 200
  out = "out"
  script = "sol_script"
  solc = "0.8.19"
  src = "contracts"
  test = "sol_test"

[profile.lite]
  fuzz = { runs = 50 }
  invariant = { runs = 10 }
  # Speed up compilation and tests during development.
  optimizer = false

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  # ETHEREUM
  goerli = { key = "${ETHERSCAN_API_KEY}" }
  mainnet = { key = "${ETHERSCAN_API_KEY}" }
  sepolia = { key = "${ETHERSCAN_API_KEY}" }

  # BINANCE SMART CHAIN
  bnb_smart_chain = { key = "${BSCSCAN_API_KEY}" }
  bnb_smart_chain_testnet = { key = "${BSCSCAN_API_KEY}" }

  # MATIC/POLYGON
  polygon = { key = "${POLYGONSCAN_API_KEY}" }
  polygon_mumbai = { key = "${POLYGONSCAN_API_KEY}" }

  # OPTIMISM
  optimism = { key = "${OPTIMISM_API_KEY}" }
  optimism_goerli = { key = "${OPTIMISM_API_KEY}" }

  # ARBITRUM
  arbitrum_nova = { key = "${ARBISCAN_API_KEY}" }
  arbitrum_one = { key = "${ARBISCAN_API_KEY}" }
  arbitrum_one_goerli = { key = "${ARBISCAN_API_KEY}" }

  # AVALANCHE
  avalanche = { key = "${SNOWTRACE_API_KEY}" }
  avalanche_fuji = { key = "${SNOWTRACE_API_KEY}" }

  # GNOSIS CHAIN
  gnosis_chain = { key = "${GNOSISSCAN_API_KEY}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 100
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  # LOCALHOST
  localhost = "http://localhost:8545"

  # ETHEREUM
  goerli = "https://goerli.infura.io/v3/${API_KEY_INFURA}"
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  sepolia = "https://sepolia.infura.io/v3/${API_KEY_INFURA}"

  # BINANCE SMART CHAIN
  bnb_smart_chain = "https://bsc-dataseed.binance.org"
  bnb_smart_chain_testnet = "https://rpc.ankr.com/bsc_testnet_chapel"

  # MATIC/POLYGON
  polygon = "https://polygon-mainnet.infura.io/v3/${API_KEY_INFURA}"
  polygon_mumbai = "https://polygon-mumbai.infura.io/v3/${INFURA_API_KEY}"

  # OPTIMISM
  optimism = "https://optimism-mainnet.infura.io/v3/${API_KEY_INFURA}"
  optimism_goerli = "https://optimism-goerli.infura.io/v3/${INFURA_API_KEY}"

  # ARBITRUM
  arbitrum_nova = ""
  arbitrum_one = "https://arbitrum-mainnet.infura.io/v3/${API_KEY_INFURA}"
  arbitrum_one_goerli = "https://arbitrum-goerli.infura.io/v3/${INFURA_API_KEY}"

  # AVALANCHE
  avalanche = "https://avalanche-mainnet.infura.io/v3/${API_KEY_INFURA}"
  avalanche_fuji = "https://avalanche-fuji.infura.io/v3/${API_KEY_INFURA}"

  # GNOSIS CHAIN
  gnosis_chain = "https://rpc.gnosischain.com"
