# Full reference https://github.com/foundry-rs/foundry/tree/master/config


[profile.default]
  auto_detect_solc = false
  bytecode_hash = "none"
  cbor_metadata = false
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  libs = ["node_modules", "lib"]
  optimizer = true
  optimizer_runs = 200
  out = "out"
  solc = "0.8.18"
  src = "contracts"
  script = "sol_script"
  test = "sol_test"

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  ethereum = { key = "${ETHERSCAN_API_KEY}" }
  goerli = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 100
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  ethereum = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
  localhost = "http://localhost:8545"
  goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}"

  # # ETHEREUM
  # mainnet = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
  # goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}"
  # sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
  # # BINANCE SMART CHAIN
  # bsc = "https://bsc.infura.io/v3/${INFURA_API_KEY}"
  # bsc-testnet = "https://bsc-testnet.infura.io/v3/${INFURA_API_KEY}"
  # # POLYGON
  # polygon-mainnet = "https://polygon-mainnet.infura.io/v3/${INFURA_API_KEY}"
  # polygon-mumbai = "https://polygon-mumbai.infura.io/v3/${INFURA_API_KEY}"
  # # OPTIMISM
  # optimism = "https://optimism.infura.io/v3/${INFURA_API_KEY}"
  # optimism-goerli = "https://optimism-goerli.infura.io/v3/${INFURA_API_KEY}"
  # # ARBITRUM
  # arbitrum = "https://arbitrum.infura.io/v3/${INFURA_API_KEY}"
  # arbitrum-goerli = "https://arbitrum-goerli.infura.io/v3/${INFURA_API_KEY}"

  # [etherscan]
  # # ETHEREUM
  # mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api", chain = "mainnet" }
  # goerli = { key = "${ETHERSCAN_API_KEY}", url = "https://api-goerli.etherscan.io/api", chain = "goerli" }
  # sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api", chain = "sepolia" }
  # # BINANCE SMART CHAIN
  # bsc = { key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api", chain = "bsc" }
  # bscTestnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api", chain = "bsc-testnet" }
  # # MATIC/POLYGON
  # polygon = { key = "${POLYGONSCAN_API_KEY}", url = "https://api.polygonscan.com/api", chain = "polygon-mainnet" }
  # polygonMumbai = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-testnet.polygonscan.com/api", chain = "polygon-mumbai" }
  # # OPTIMISM
  # optimisticEthereum = { key = "${OPTIMISM_API_KEY}", url = "https://api-optimistic.etherscan.io/api", chain = "optimism" }
  # optimisticGoerli = { key = "${OPTIMISM_API_KEY}", url = "https://api-goerli-optimism.etherscan.io/api", chain = "optimism-goerli" }
  # # ARBITRUM
  # arbitrumOne = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api", chain = "arbitrum" }
  # arbitrumTestnet = { key = "${ARBISCAN_API_KEY}", url = "https://api-goerli.arbiscan.io/api", chain = "arbitrum-goerli" }
