# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
auto_detect_solc = false
broadcast = "broadcast"
bytecode_hash = "none"
cache_path = "foundry_cache"
fuzz_runs = 256
gas_reports = ["*"]
libs = ["node_modules", "lib"]
optimizer = true
optimizer_runs = 200
out = "out"
solc = "0.8.17"
src = "contracts"
script = "sol_script"
test = "sol_test"

[profile.ci]
fuzz_runs = 1_000
verbosity = 4

[rpc_endpoints]
# ETHEREUM
mainnet = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
# BINANCE SMART CHAIN
bsc = "https://bsc.infura.io/v3/${INFURA_API_KEY}"
bsc-testnet = "https://bsc-testnet.infura.io/v3/${INFURA_API_KEY}"
# POLYGON
polygon-mainnet = "https://polygon-mainnet.infura.io/v3/${INFURA_API_KEY}"
polygon-mumbai = "https://polygon-mumbai.infura.io/v3/${INFURA_API_KEY}"
# OPTIMISM
optimism = "https://optimism.infura.io/v3/${INFURA_API_KEY}"
optimism-goerli = "https://optimism-goerli.infura.io/v3/${INFURA_API_KEY}"
# ARBITRUM
arbitrum = "https://arbitrum.infura.io/v3/${INFURA_API_KEY}"
arbitrum-goerli = "https://arbitrum-goerli.infura.io/v3/${INFURA_API_KEY}"

[etherscan]
# ETHEREUM
mainnet = {key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api"}
goerli = {key = "${ETHERSCAN_API_KEY}", url = "https://api-goerli.etherscan.io/api"}
sepolia = {key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api"}
# BINANCE SMART CHAIN
bsc = {key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api"}
bscTestnet = {key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api"}
# MATIC/POLYGON
polygon = {key = "${POLYGONSCAN_API_KEY}", url = "https://api.polygonscan.com/api"}
polygonMumbai = {key = "${POLYGONSCAN_API_KEY}", url = "https://api-testnet.polygonscan.com/api"}
# OPTIMISM
optimisticEthereum = {key = "${OPTIMISM_API_KEY}", url = "https://api-optimistic.etherscan.io/api"}
optimisticGoerli = {key = "${OPTIMISM_API_KEY}", url = "https://api-goerli-optimism.etherscan.io/api"}
# ARBITRUM
arbitrumOne = {key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api"}
arbitrumTestnet = {key = "${ARBISCAN_API_KEY}", url = "https://api-goerli.arbiscan.io/api"}
