name: "CI"

env:
  FOUNDRY_PROFILE: "ci"
  DOTENV_CONFIG_PATH: "./.env.example"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Install Foundry and restore the RPC cache, if any"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "lts/*"

      - name: "Install the Node.js dependencies"
        run: "yarn install --immutable --inline-builds"

      - name: "Lint solidity code"
        run: "yarn lint:sol"

      - name: "Add lint summary"
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Hardhat"
        run: |
          echo "
            /*//////////////////////////////////////////////////////////////
                                        HARDHAT
            //////////////////////////////////////////////////////////////*/
          "

      - name: "Compile the contracts and generate the TypeChain bindings"
        run: "yarn typechain"

      - name: "Generate the coverage report"
        run: "yarn coverage"

      - name: "Add Hardhat coverage summary"
        run: |
          echo "## Coverage results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Foundry"
        run: |
          echo "
            /*//////////////////////////////////////////////////////////////
                                        FOUNDRY
            //////////////////////////////////////////////////////////////*/
          "

      - name: "Show the Foundry config"
        run: "forge config"

      - name: "Generate fuzz seed that changes weekly to avoid burning through RPC allowance"
        run: >
          echo "FOUNDRY_FUZZ_SEED=$(
            echo $(($EPOCHSECONDS - $EPOCHSECONDS % 604800))
          )" >> $GITHUB_ENV

      - name: "Run forge tests"
        run: "forge test"

      - name: "Check that the contracts are each under 24kB"
        run: |
          forge --version
          forge build --sizes

      - name: "Add forge test summary"
        run: |
          echo "## Foundry Tests" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
