name: "CI"

env:
  FOUNDRY_PROFILE: "ci"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Install Foundry"
        uses: "onbjerg/foundry-toolchain@v1"
        with:
          version: "nightly"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "16"

      # Inject all environment variables from ".env.example" in $GITHUB_ENV
      - name: "Set dotenv"
        uses: "c-py/action-dotenv-to-setenv@v2"
        with:
          env-file: ".env.example"

      - name: "Install the Node.js dependencies"
        run: "yarn install --immutable"

      - name: "Lint solidity code"
        run: "yarn lint:sol"

      - name: "Add lint summary"
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Hardhat"
        run: |
          echo "
              /*//////////////////////////////////////////////////////////////
                                HARDHAT
              //////////////////////////////////////////////////////////////*/
          "

      - name: "Compile the contracts and generate the TypeChain bindings"
        run: "yarn typechain"

      - name: "Generate the coverage report"
        run: "yarn coverage"

      - name: "Add coverage summary"
        run: |
          echo "## Coverage results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Foundry"
        run: |
          echo "
            /*//////////////////////////////////////////////////////////////
                                        FOUNDRY
            //////////////////////////////////////////////////////////////*/
          "

      - name: "Show the Foundry config"
        run: "forge config"

      - name: "Run forge tests"
        run: "forge test"

      - name: "Build the contracts"
        run: |
          forge --version
          forge build --sizes

      - name: "Add forge test summary"
        run: |
          echo "## Tests" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
